export interface Ability {
  Id: number;
  BaseId: number;
  BaseIdNumeral: number;
  TextId: number;
  OldSchoolManaText: string | null;
  Category: number;
  SubCategory: number;
  AbilityWord: number;
  NumericAid: number;
  RequiresConfirmation: number;
  MiscellaneousTerm: number;
  PaymentType: number;
  LoyaltyCost: string | null;
  FullyParsed: number;
  IsIntrinsicAbility: number;
  RelevantZones: string | null;
  HiddenAbilityIds: string | null;
  HiddenByAbilityIds: string | null;
  ReferencedAbilityIds: string | null;
  ReferencedAbilityTypes: string | null;
  ModalChildIds: string | null;
  ModalParentIds: string | null;
  CostTypes: string | null;
}

export interface Card {
  GrpId: number;
  ArtId: number;
  ArtPath: string;
  TitleId: number;
  AltTitleId: 0;
  FlavorTextId: number;
  TypeTextId: number;
  SubtypeTextId: number;
  ArtistCredit: string;
  ArtSize: number;
  Rarity: number;
  ExpansionCode: string;
  DigitalReleaseSet: string;
  IsToken: number;
  IsPrimaryCard: number;
  IsDigitalOnly: number;
  IsRebalanced: number;
  RebalancedCardGrpId: number;
  DefunctRebalancedCardGrpId: number;
  AlternateDeckLimit: number;
  CollectorNumber: string;
  CollectorMax: string;
  UsesSideboard: number;
  OldSchoolManaText: string;
  LinkedFaceType: number;
  RawFrameDetail: string;
  Watermark: string;
  TextChangeData: string;
  Tags: string;
  Power: string;
  Toughness: string;
  Colors: string;
  ColorIdentity: string;
  FrameColors: string;
  IndicatorColors: string;
  Types: string;
  Subtypes: string;
  Supertypes: string;
  AbilityIds: string;
  HiddenAbilityIds: string;
  LinkedFaceGrpIds: string;
  LinkedAbilityTemplateCardGrpIds: string;
  AbilityIdToLinkedTokenGrpId: string;
  AbilityIdToLinkedConjurations: string;
  KnownSupportedStyles: string;
  AdditionalFrameDetails: string;
  ExtraFrameDetails: string;
  Order_LandLast: number | null;
  Order_ColorOrder: number | null;
  Order_CreaturesFirst: number | null;
  Order_ManaCostDifficulty: number | null;
  Order_CMCWithXLast: number | null;
  Order_Title: string | null;
  Order_MythicToCommon: number | null;
  Order_BasicLandsFirst: number | null;
  ReminderTextId: number;
}
